PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS grants(id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY, grant_id TEXT NOT NULL REFERENCES grants(id), request TEXT NOT NULL, status TEXT NOT NULL, result TEXT, started_ms TEXT NOT NULL, finished_ms TEXT);
CREATE TABLE IF NOT EXISTS checkpoints(run_id TEXT PRIMARY KEY REFERENCES runs(id), body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(cursor INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, client TEXT NOT NULL, project TEXT NOT NULL, run_id TEXT NOT NULL, producer TEXT NOT NULL, sequence TEXT NOT NULL, split TEXT NOT NULL, body TEXT NOT NULL, UNIQUE(client,project,run_id,producer,sequence));
CREATE INDEX IF NOT EXISTS events_scope ON events(client,project,cursor);
CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY, client TEXT NOT NULL, project TEXT NOT NULL, kind TEXT NOT NULL, version TEXT NOT NULL, split TEXT NOT NULL, body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS records_scope ON records(client,project,kind);
CREATE VIRTUAL TABLE IF NOT EXISTS record_search USING fts5(id UNINDEXED,content);
CREATE TABLE IF NOT EXISTS dependencies(client TEXT NOT NULL, project TEXT NOT NULL, source TEXT NOT NULL, dependent TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(client,project,source,dependent));
CREATE TABLE IF NOT EXISTS invalidated(client TEXT NOT NULL, project TEXT NOT NULL, path TEXT NOT NULL, PRIMARY KEY(client,project,path));
CREATE TABLE IF NOT EXISTS effects(id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), grant_id TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS branches(id TEXT PRIMARY KEY, grant_id TEXT NOT NULL, path TEXT NOT NULL, versions TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work(id TEXT PRIMARY KEY, grant_id TEXT NOT NULL, root_id TEXT NOT NULL, subject TEXT NOT NULL, status TEXT NOT NULL, lease_until_ms INTEGER NOT NULL, body TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS work_active_subject ON work(grant_id,subject) WHERE status IN ('queued','running','interrupted');
CREATE TABLE IF NOT EXISTS messages(sequence INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, grant_id TEXT NOT NULL, sender TEXT NOT NULL, recipient TEXT NOT NULL, acknowledged INTEGER NOT NULL DEFAULT 0, attempts INTEGER NOT NULL DEFAULT 0, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS permits(id TEXT PRIMARY KEY, grant_id TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES runs(id), reserved_tokens INTEGER NOT NULL, reserved_cost INTEGER NOT NULL, usage TEXT);
CREATE TABLE IF NOT EXISTS archive(client TEXT NOT NULL, project TEXT NOT NULL, context TEXT NOT NULL, policy_id TEXT NOT NULL, cell TEXT NOT NULL, implementation_id TEXT NOT NULL, quality REAL NOT NULL, evaluation_id TEXT NOT NULL, PRIMARY KEY(client,project,context,policy_id,cell));
CREATE TABLE IF NOT EXISTS experiments(id TEXT PRIMARY KEY,grant_id TEXT NOT NULL,policy_id TEXT NOT NULL,policy TEXT NOT NULL,result TEXT);
CREATE TABLE IF NOT EXISTS subscriptions(id TEXT PRIMARY KEY,body TEXT NOT NULL,cursor TEXT NOT NULL,pending TEXT NOT NULL,first_pending_ms TEXT NOT NULL);
PRAGMA user_version=1;
